language: julia
os:
    - linux
    - osx
julia:
    - 0.6
    - 0.7
    - nightly
notifications:
    email: false
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'Pkg.clone(pwd()); Pkg.build("HttpParser")'
    - julia -e 'Pkg.test("HttpParser", coverage=true)'
after_success:
    - julia -e 'cd(Pkg.dir("HttpParser")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
